In [17]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.231 seconds
All requested packages already installed.

In [21]:
import pandas as pd
print(pd.__version__)

3.0.5

In [22]:
df = pd.read_csv("resturant_sales.csv")

In [23]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [24]:
df.shape

(254, 9)

In [25]:
df.columns

Index(['Order ID', 'Date', 'Product', 'Price', 'Quantity', 'Purchase Type',
       'Payment Method', 'Manager', 'City'],
      dtype='str')

In [26]:
df.dtypes

Order ID            int64
Date                  str
Product               str
Price             float64
Quantity          float64
Purchase Type         str
Payment Method        str
Manager               str
City                  str
dtype: object

In [27]:
df.isnull().sum()

Order ID          0
Date              0
Product           0
Price             0
Quantity          0
Purchase Type     0
Payment Method    0
Manager           0
City              0
dtype: int64

In [28]:
df = df.drop_duplicates()

In [29]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

In [30]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-11-07,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,2022-11-07,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-11-07,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-11-08,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [31]:
text_columns = ["Product", "Purchase Type", "Payment Method", "Manager", "City"]

for col in text_columns:
    df[col] = df[col].str.strip()

In [32]:
df.head(20)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-11-07,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,2022-11-07,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-11-07,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-11-08,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin
5,10457,2022-11-08,Fries,3.49,573.07,In-store,Credit Card,Remy Monet,Paris
6,10459,2022-11-08,Sides & Other,4.99,200.40,In-store,Credit Card,Walter Muller,Berlin
7,10460,2022-11-09,Burgers,12.99,554.27,In-store,Credit Card,Remy Monet,Paris
8,10461,2022-11-09,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Remy Monet,Paris
9,10462,2022-11-09,Fries,3.49,573.07,In-store,Credit Card,Remy Monet,Paris
10,10463,2022-11-09,Beverages,2.95,677.97,In-store,Credit Card,Remy Monet,Paris
11,10464,2022-11-09,Sides & Other,4.99,200.40,In-store,Credit Card,Remy Monet,Paris
12,10465,2022-11-10,Burgers,12.99,554.27,In-store,Credit Card,Pablo Perez,Madrid
13,10466,2022-11-10,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Pablo Perez,Madrid
14,10467,2022-11-10,Fries,3.49,573.07,In-store,Credit Card,Pablo Perez,Madrid
15,10468,2022-11-10,Beverages,2.95,677.97,In-store,Credit Card,Pablo Perez,Madrid
16,10470,2022-11-11,Burgers,12.99,554.27,In-store,Credit Card,Pablo Perez,Madrid
17,10471,2022-11-11,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Pablo Perez,Madrid
18,10472,2022-11-11,Fries,3.49,630.37,In-store,Credit Card,Pablo Perez,Madrid
19,10473,2022-11-11,Beverages,2.95,677.97,In-store,Credit Card,Pablo Perez,Madrid

In [33]:
df[["Price", "Quantity"]].describe()

            Price    Quantity
count  254.000000  254.000000
mean     7.102323  460.611457
std      4.341855  214.888699
min      2.950000  200.400000
25%      3.490000  201.010000
50%      4.990000  538.880000
75%      9.950000  677.440000
max     29.050000  754.430000

In [34]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [35]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-11-07,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,2022-11-07,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-11-07,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-11-08,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [36]:
df.isnull().sum()

Order ID          0
Date              0
Product           0
Price             0
Quantity          0
Purchase Type     0
Payment Method    0
Manager           0
City              0
dtype: int64

In [37]:
df["Total Sales"] = df["Price"] * df["Quantity"]

In [38]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Total Sales
0,10452,2022-11-07,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London,2000.0143
1,10453,2022-11-07,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid,2199.9920
2,10454,2022-11-07,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon,999.9960
3,10455,2022-11-08,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin,7400.0133
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin,2000.0495

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    datetime64[us]
 2   Product         254 non-null    str
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    str
 6   Payment Method  254 non-null    str
 7   Manager         254 non-null    str
 8   City            254 non-null    str
 9   Total Sales     254 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(1), str(5)
memory usage: 15.0 KB

In [40]:
df.to_csv("cleaned_sales_data.csv", index=False)